# Generated by Django 5.2.17 on 2026-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='expected_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Required code/output tokens'),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_criteria',
            field=models.JSONField(blank=True, default=list, help_text='Automated test criteria list'),
        ),
    ]
