# Generated by Django 5.2.17 on 2026-09-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_problem_expected_keywords_problem_test_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed course/subject overview')),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(default='code', help_text='Icon identifier e.g. django, python, code, database', max_length=50)),
                ('banner_image', models.TextField(blank=True, default='')),
                ('instructor_name', models.CharField(default='Lead Instructor', max_length=150)),
                ('level', models.CharField(default='Beginner to Advanced', max_length=50)),
                ('duration', models.CharField(default='8 Weeks', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.subject'),
        ),
    ]
