# Generated by Django 4.2.30 on 2026-09-09 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0003_subject_module_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. C Programming - Morning Batch A (10:00 AM)', max_length=150)),
                ('schedule', models.CharField(default='Mon-Wed-Fri 10:00 AM - 12:00 PM', max_length=150)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active / Ongoing'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20)),
                ('max_students', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Course / Subject', 'verbose_name_plural': 'Courses / Subjects'},
        ),
        migrations.AddField(
            model_name='problem',
            name='expected_output',
            field=models.TextField(blank=True, default='', help_text='The exact answer key output string used for automated validation'),
        ),
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('c', 'C Programming'), ('javascript', 'JavaScript (Node.js)'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='schedule_type',
            field=models.CharField(default='3 days class + 3 days lab per week', help_text='e.g. 3 days class + 3 days lab per week', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='notes_content',
            field=models.TextField(blank=True, default='', help_text='Rich markdown/text study notes for the topic'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(help_text='Detailed problem statement & instructions'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='expected_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Required code/syntax tokens'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='expected_output_hint',
            field=models.TextField(blank=True, default='', help_text='Public hint shown to student'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(blank=True, default='', help_text='Initial starter template code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed course overview'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='duration',
            field=models.CharField(default='8 Weeks', help_text='e.g. 8 Weeks / 45 Days', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='code', help_text='Icon identifier e.g. python, c, code, database', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='instructor_name',
            field=models.CharField(default='Lead Trainer', max_length=150),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Course name e.g. C Programming, Python, Django', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='explain',
            field=models.JSONField(blank=True, default=list, help_text='List of explanation points/paragraphs'),
        ),
        migrations.CreateModel(
            name='StaffDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('session_type', models.CharField(choices=[('TOPIC', 'Topic / Theory Class'), ('LAB', 'Lab Practice Session'), ('DOUBT', 'Doubt Clearing / Review'), ('ASSESSMENT', 'Assessment / Test')], default='TOPIC', max_length=30)),
                ('session_title', models.CharField(blank=True, default='', help_text="Topic name covered or 'Lab'", max_length=200)),
                ('total_enrolled', models.PositiveIntegerField(default=0)),
                ('students_attended', models.PositiveIntegerField(default=0, help_text='Aggregate attended student count filled by staff')),
                ('remarks', models.TextField(blank=True, default='', help_text='Free text notes/remarks by staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='curriculum.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='curriculum.subject')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_logs', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='curriculum.topic')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(help_text='Linked course (supports duplicate course names across separate batches)', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='batch',
            name='staff',
            field=models.ManyToManyField(blank=True, help_text='Assigned staff trainers', related_name='assigned_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Enrolled students in this batch', related_name='enrolled_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_records', to='curriculum.staffdailylog')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('daily_log', 'student')},
            },
        ),
        migrations.CreateModel(
            name='BatchTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='Independent topic completion flag')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='curriculum.batch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_topic_progress', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_progress', to='curriculum.topic')),
            ],
            options={
                'ordering': ['topic__order', 'id'],
                'unique_together': {('batch', 'topic')},
            },
        ),
    ]
