# Generated by Django 4.2.30 on 2026-09-09 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_batch_alter_subject_options_problem_expected_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3'), ('c', 'C Programming'), ('javascript', 'JavaScript (Node.js)'), ('cpp', 'C++'), ('java', 'Java'), ('excel', 'MS Excel / Spreadsheet Task'), ('word', 'MS Word & Documentation Task'), ('tally', 'Tally Prime / Accounting Entry'), ('sql', 'SQL & Database Query'), ('general', 'General Practical Exercise / Task')], default='python', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffdailylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
