# Generated by Django 5.2.17 on 2026-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_batch_start_date_alter_problem_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
