# Generated by Django 5.2.17 on 2026-09-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_topic_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(help_text='Public Supabase Storage URL of the uploaded image')),
                ('caption', models.CharField(blank=True, default='', help_text='Optional caption shown below image', max_length=300)),
                ('order', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='curriculum.topic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
