# Generated by Django 5.2.17 on 2026-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_topicimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', help_text='Display number e.g. 01, 02, 03', max_length=5)),
                ('title', models.CharField(help_text='Card heading', max_length=200)),
                ('description', models.TextField(help_text='Card body description shown on website')),
                ('icon', models.CharField(blank=True, default='code', help_text='Icon identifier: code, layers, terminal, award, cpu, shield, database', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from website')),
            ],
            options={
                'verbose_name': 'Platform Capability / Feature Card',
                'verbose_name_plural': 'Platform Capabilities / Feature Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
