# Generated by Django 4.2.30 on 2026-09-11 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0008_add_platform_capability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question prompt')),
                ('option_a', models.TextField(help_text='Choice A')),
                ('option_b', models.TextField(help_text='Choice B')),
                ('option_c', models.TextField(help_text='Choice C')),
                ('option_d', models.TextField(help_text='Choice D')),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', help_text='Correct answer letter (A, B, C, or D)', max_length=2)),
                ('explanation', models.TextField(blank=True, default='', help_text='Detailed explanation shown during review')),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='curriculum.topic')),
            ],
            options={
                'verbose_name': 'Topic Quiz Question',
                'verbose_name_plural': 'Topic Quiz Questions',
                'ordering': ['topic', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Number of correct answers')),
                ('total_questions', models.PositiveIntegerField(default=5, help_text='Total questions served in this attempt')),
                ('percentage', models.FloatField(default=0.0, help_text='Percentage score achieved')),
                ('is_passed', models.BooleanField(default=False, help_text='True if percentage >= 50.0')),
                ('status', models.CharField(choices=[('PASSED', 'Passed (>= 50%)'), ('FAILED_SCORE', 'Failed - Score Under 50%'), ('FAILED_SECURITY', 'Terminated - Security Violation (Tab switch / devtools)')], default='FAILED_SCORE', max_length=25)),
                ('security_violations', models.PositiveIntegerField(default=0, help_text='Count of security infractions recorded')),
                ('violation_details', models.TextField(blank=True, default='', help_text='Log of security warnings / exit triggers')),
                ('questions_data', models.JSONField(blank=True, default=list, help_text='Snapshot of the 5 questions & choices served')),
                ('selected_answers', models.JSONField(blank=True, default=dict, help_text='Map of question_id -> chosen option')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, help_text='Time taken to finish the test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='curriculum.topic')),
            ],
            options={
                'verbose_name': 'Topic Quiz Attempt',
                'verbose_name_plural': 'Topic Quiz Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='True if student scored >= 50% on the topic quiz')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('last_score', models.PositiveIntegerField(default=0)),
                ('last_total', models.PositiveIntegerField(default=5)),
                ('last_percentage', models.FloatField(default=0.0)),
                ('last_passed', models.BooleanField(default=False)),
                ('can_reattempt_after', models.DateTimeField(blank=True, help_text='10-minute cooldown timestamp set if test was failed. Cannot re-attempt until this expires.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress_records', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress_records', to='curriculum.topic')),
            ],
            options={
                'verbose_name': 'Student Topic Progress',
                'verbose_name_plural': 'Student Topic Progress Records',
                'ordering': ['topic__order', 'id'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
