# Generated by Django 4.2.30 on 2026-09-17 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_topicquizquestion_topicquizattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content_type', models.CharField(default='image/png', max_length=100)),
                ('data', models.BinaryField(help_text='Binary image payload stored in database')),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
