# Generated by Django 4.2.30 on 2026-09-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_batch_alter_subject_options_problem_expected_output_and_more'),
        ('users', '0002_user_assigned_subject_user_is_admin_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff_users', to='curriculum.subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='batch_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / Owner'), ('STAFF', 'Staff / Trainer'), ('STUDENT', 'Student / Learner')], default='STUDENT', max_length=10),
        ),
    ]
