# Generated by Django 5.2.17 on 2026-09-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False, help_text='Staff toggles this to make problem accessible to students')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='Timestamp after which students can no longer submit', null=True)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('batch_name', models.CharField(default='All', max_length=100)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to='curriculum.problem')),
            ],
            options={
                'verbose_name': 'Problem Access & Timeline',
                'verbose_name_plural': 'Problem Access Controls',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(help_text="Student's submitted code or answers")),
                ('notes', models.TextField(blank=True, default='', help_text='Optional student execution log or comments')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted - Pending Review'), ('PASSED', 'Approved / Passed'), ('REVISION_REQUESTED', 'Revision Requested'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=25)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_feedback', models.TextField(blank=True, default='')),
                ('is_late', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='curriculum.problem')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
