# Generated by Django 4.2.30 on 2026-09-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_batch_alter_subject_options_problem_expected_output_and_more'),
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemaccess',
            options={'verbose_name': 'Problem Access Control', 'verbose_name_plural': 'Problem Access Controls'},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='problemaccess',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_access_controls', to='curriculum.batch'),
        ),
        migrations.AddField(
            model_name='submission',
            name='actual_output',
            field=models.TextField(blank=True, default='', help_text='Captured console output from execution'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='curriculum.batch'),
        ),
        migrations.AddField(
            model_name='submission',
            name='error_detail',
            field=models.TextField(blank=True, default='', help_text='Full compiler or runtime trace'),
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_time_ms',
            field=models.FloatField(default=0.0, help_text='Execution duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='submission',
            name='expected_output',
            field=models.TextField(blank=True, default='', help_text='Target expected output key'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='problemaccess',
            name='allow_late_submission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='problemaccess',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemaccess',
            name='is_unlocked',
            field=models.BooleanField(default=True, help_text='Toggles whether problem is visible to students'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Student comments or notes'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PASSED', 'Passed / Correct'), ('FAILED', 'Incorrect Output'), ('COMPILE_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('TIMEOUT', 'Execution Timeout'), ('SUBMITTED', 'Submitted - Pending Review')], default='SUBMITTED', max_length=25),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_code',
            field=models.TextField(help_text="Student's submitted code"),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_late',
        ),
    ]
