# Generated by Django 4.2.30 on 2026-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_problemaccess_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemaccess',
            name='is_unlocked',
            field=models.BooleanField(default=False, help_text='Toggles whether problem is visible to students'),
        ),
    ]
