# Generated by Django 4.2.30 on 2026-09-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_problemaccess_is_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='security_violations',
            field=models.PositiveIntegerField(default=0, help_text='Security tab switch or devtools infractions'),
        ),
        migrations.AddField(
            model_name='submission',
            name='violation_details',
            field=models.TextField(blank=True, default='', help_text='Security infraction logs'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PASSED', 'Passed / Correct'), ('FAILED', 'Incorrect Output'), ('COMPILE_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('TIMEOUT', 'Execution Timeout'), ('FAILED_SECURITY', 'Terminated - Security Violation'), ('SUBMITTED', 'Submitted - Pending Review')], default='SUBMITTED', max_length=25),
        ),
    ]
